<style>
    .add, .back {
        border-bottom:1px dotted #627D90;
        padding-bottom:10px;
    }

    .back{margin-bottom: 20px;}

    .button_menu{
        height: 10px;
        padding-top: 10px;
    }
    .button_menu a.menu, .add a.menu, #paging a.menu, #yearSelector a.menu, .back a.menu{
        padding: 0 10px;
        background-color: #F57912;
        color: #FFF;
        margin-left: 5px;
    }

    .button_menu a.menu {float: right;}

    #paging{
        margin-top:20px;
        margin-bottom: 10px;
    }

    #paging a.page{
        border:1px solid #134B7C;
        color:black;width:20px;
        text-align:center;
        background-color:#D9DFE4;
        display:block;float:left;
        margin-right:3px;
        margin-bottom:3px;
        width: 30px;
        padding-top: 2px;
        padding-bottom: 2px;
    }

    #paging .clearer{
        height:10px;
        width:10px;
        float:left;
    }

    #yearselector{height: 60px;}

    #yearselector #submit{
        padding: 2px 10px;
        background-color: #F57912;
        color: #FFF;
        margin-left: 5px;
        border: none;
        cursor: pointer;
    }

    .clearfix:after {
        content: ".";
        display: block;
        clear: both;
        visibility: hidden;
        line-height: 0;
        height: 0;
    }

    div.item img.events_logo{
        float: left;
        max-width: 170px;
        height: auto;
        padding-top: 10px;
        max-height: 110px;
    }
</style>
<div class="back"  >
    <a class="menu" href="<?php echo $this->baseUrl ?>"><?php
        if ($this->lang == "en") {
            $back = "back";
        }
        else {
            $back = "zur&uuml;ck";
        }
        echo $back;
        ?></a>
</div>

<?php if (!empty($this->array)) : ?>
    <?php foreach ($this->array as $entry) : ?>
        <div class="item">

            <div style="margin-top:10px;color:#627D90;">
                <?php
                $year = substr($entry['free_date'], 0, 4);
                $month = substr($entry['free_date'], 4, 2);
                $day = substr($entry['free_date'], 6, 2);

                $date2 = "";
                if ($entry["opt7text"] != $entry["free_date"]) {
                    $year2 = substr($entry['opt7text'], 0, 4);
                    $month2 = substr($entry['opt7text'], 4, 2);
                    $day2 = substr($entry['opt7text'], 6, 2);

                    $date2 = ' - ' . $day2 . '.' . $month2 . '.' . $year2;
                }
                echo $day . '.' . $month . '.' . $year . $date2;
                ?>
            </div>

            <h1><?php echo $entry["description"] ?></h1>

            <h2><?php echo $entry["opt4text"] ?></h2>


            <div style="border-bottom:1px dotted #627D90;padding-bottom:10px;">
                <p>
                    <?php
                    if (!empty($entry["url"])) {
                        if ($this->lang == "en") {
                            $more = "more";
                        }
                        else {
                            $more = "mehr";
                        }
                        
                        if (strstr($entry["url"], '[[intern:')) {
                            $dummy = str_replace('[[intern:', '', $entry["url"]);
                            $pid = str_replace(']]', '', $dummy);
                            $pid = intval(trim($pid));
                            
                            $url = $this->baseUrlWithoutIndex.$pid;
                        }else{
                            $url = $entry["url"];
                        }

                        echo $entry["info"];
                        
                        echo "...[<a class=\"extern\" target=\"_blank\" href=\"" . $url . "\">" . $more . "</a>]";
                    }else{
                        echo $entry["info"];
                    }
                    ?></p>
            </div>
        </div>
    <?php endforeach; ?>
<?php else : ?>
    <div class="item">
        <div class="button_menu">
            <p><?php
                if ($this->lang == "en") {
                    $out = "no entries available";
                }
                else {
                    $out = "keine Eintr&auml;ge vorhanden";
                }
                echo $out;
                ?></p>
        </div>
    </div>
<?php endif; ?>
<div id="paging">
    <a class="menu" href="<?php echo $this->baseUrl ?>"><?php
        if ($this->lang == "en") {
            $back = "back";
        }
        else {
            $back = "zur&uuml;ck";
        }
        echo $back;
        ?></a>
</div>